### ISSUE TITLE
Starting a new project says .... "project name is required ... 

### ISSUE THREAD

**Issue by uwerichter** [DataJuggler/DataTier.Net#18]
But i've one given. 
And than it says: the Folder .. \repos\MyProject.Web doesn't exist. But there is a folder.
What did i do wrong.

**Comment by DataJuggler** [comment]
I just encountered this same issue, and I think the cause is when another folder isn't found like the project templates didn't install even though the message says it did. What just fixed the issue for me was to click Run Setup Again, then click Install Dot Net Core Project Templates.
I have upgraded Visual Studio dozens of times since I installed the templates, and it seemed I had to install them again today to get the Project Editor > Creator Data Tier in Project Folder to work.

I kind of rushed the command line Nuget installs without thoroughly testing. I will work on polishing up the failures to explain what went wrong and match the message with the actual error if I can.

I am just curious, are you creating a Dot Net Core or Dot Net Framework project?

Sorry I didn't respond sooner. I will make a note to check the issues on a regular basis.

I just created a project after watching my own video again, and it worked.
Maybe this will help: https://youtu.be/sowTLLeAfm8

**Comment by DataJuggler** [comment]
This has been fixed today. Version 2.4.3 now installs the Project templates each time you install, which seems to be needed in case you updated Visual Studio since the last time and it now checks for 5 seconds in a loop until the project is created before it shows you a true or false message.

**Comment by DataJuggler** [comment]
Sorry for the long delay, I was stuck on other Blazor projects.
